### ISSUE TITLE
Questions on the paper writing

### ISSUE THREAD

**Issue by hbr690188270** [THU-KEG/ChatLog#3]
Very impressive paper. But may I raise a question about some statements in the paper? I found some statements about mathematical reasoning might be not rigorous enough. It seems the authors may have unintentionally used the term "MathQA dataset" to refer to the GSM8K dataset, which could lead to confusion for readers. It would be great to clarify this in the paper and use the correct terminology to avoid any misunderstandings. The corresponding statements include:
- "ChatGPT has improved significantly, which can tell from its accuracy increase from 71.40% to 78.00% on the MathQA dataset." **Location: Section 3.2 (3)**
- "Task Name: MathQA" **Location: Table 2**
- "One error example of ChatGPT’s January version on MathQA dataset." **Location: Caption of Table 3**

The key problem is, MathQA is another specific dataset from [1], which is completely different from GSM8K. GSM8K mainly focuses on **arithmetic reasoning**, and MathQA from [1] includes more diverse math word problems and is more challenging compared to GSM8K (though its annotation is noisier). According to [2], the performance of GPT-3.5 models is significantly lower on the MathQA dataset compared to the GSM8K. This makes the statements like " its accuracy increase from 71.40% to 78.00% on the MathQA dataset. " in your paper less rigorous. If we directly use the "MathQA dataset" to refer to the GSM8K dataset in the paper, we might cause unnecessary (but also very significant) misunderstandings. 

These are my personal thoughts and I am not sure if they are reasonable. It would be appreciated a lot if I can get feedback from you and these corresponding statements can be fixed in the future version (if my opinion is reasonable).

[1] Amini, Aida, et al. "Mathqa: Towards interpretable math word problem solving with operation-based formalisms." arXiv preprint arXiv:1905.13319 (2019).
[2] Fu, Yao, et al. "Complexity-based prompting for multi-step reasoning." arXiv preprint arXiv:2210.00720 (2022).

**Comment by ShangQingTu** [comment]
Thanks for your advice!
In fact, I didn't know Mathqa is another work. We follow Jack_of_all[1], where the "MathQA" actually refers to GSM8K. 
Thanks a lot for pointing out the co-reference problem. I will use GSM8K as the name in the future version of our paper.

[1] Kocoń J, Cichecki I, Kaszyca O, et al. ChatGPT: Jack of all trades, master of none[J]. arXiv, 2023.
